document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'zh-CN\'>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\'>");
document.writeln("<script type=\'text/javascript\' src=\'https://cdn.bootcss.com/echarts/4.2.1-rc1/echarts.min.js\'></script>");
document.writeln("<link rel=\'stylesheet\' href=\'scripts/layui/css/layui.css\'>");
document.writeln("<script type=\'text/javascript\' src=\'scripts/layui/layui.all.js\'></script>");
document.writeln("<title>生命不息，奋斗不止</title>");
document.writeln("<style type=\'text/css\'>");
document.writeln("table{");
document.writeln("    table-layout:fixed;");
document.writeln("    empty-cells:show; ");
document.writeln("    border-collapse: collapse;");
document.writeln("    margin:0 auto;");
document.writeln("}");
document.writeln("");
document.writeln("td{height:20px;}");
document.writeln("");
document.writeln("table.t1{");
document.writeln("    border:1px solid #cad9ea;");
document.writeln("    color:#666;");
document.writeln("	width:60%;");
document.writeln("}");
document.writeln("");
document.writeln("table td:nth-child(even){");
document.writeln("background: #f5f7ff;");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("<script>");
document.writeln("var _hmt = _hmt || [];");
document.writeln("(function() {");
document.writeln("  var hm = document.createElement(\'script\');");
document.writeln("  hm.src = \'https://hm.baidu.com/hm.js?d93be978a1838e49bc1e3470a784a378\';");
document.writeln("  var s = document.getElementsByTagName(\'script\')[0]; ");
document.writeln("  s.parentNode.insertBefore(hm, s);");
document.writeln("})();");
document.writeln("</script>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("");
document.writeln("<ul class=\'layui-timeline\'>");
document.writeln("  <li class=\'layui-timeline-item\'>");
document.writeln("    <i class=\'layui-icon layui-timeline-axis\'>&#xe63f;</i>");
document.writeln("    <div class=\'layui-timeline-content layui-text\'>");
document.writeln("      <h3 class=\'layui-timeline-title\'>2019-03-01</h3>");
document.writeln("      <p>");
document.writeln("         工商银行软件开发中心杭州研发部杭州开发一部");
document.writeln("        <br><i class=\'layui-icon layui-icon-diamond\' style=\'font-size: 20px; color: #FF0000;\'></i> 架构师");
document.writeln("        <br>信贷领域");
document.writeln("      </p>");
document.writeln("    </div>");
document.writeln("  </li>");
document.writeln("  <li class=\'layui-timeline-item\'>");
document.writeln("    <i class=\'layui-icon layui-timeline-axis\'>&#xe63f;</i>");
document.writeln("    <div class=\'layui-timeline-content layui-text\'>");
document.writeln("      <h3 class=\'layui-timeline-title\'>2018-02-26</h3>");
document.writeln("      <p><em>中国工商银行总行信贷管理部</em></p>");
document.writeln("      <ul>");
document.writeln("        <li>交流</li>");
document.writeln("        <li>对公信贷</li>");
document.writeln("      </ul>");
document.writeln("    </div>");
document.writeln("  </li>");
document.writeln("  <li class=\'layui-timeline-item\'>");
document.writeln("    <i class=\'layui-icon layui-timeline-axis\'>&#xe63f;</i>");
document.writeln("    <div class=\'layui-timeline-content layui-text\'>");
document.writeln("      <h3 class=\'layui-timeline-title\'>2009-07-06</h3>");
document.writeln("      <p>");
document.writeln("        中国工商银行软件开发中心杭州开发一部");
document.writeln("        <br>信贷系统开发");
document.writeln("        <br>开发经理、项目经理、开发人员");
document.writeln("        <br>数据挖掘、批量");
document.writeln("        <br>监管报送");
document.writeln("      </p>");
document.writeln("    </div>");
document.writeln("  </li>	");
document.writeln("  <li class=\'layui-timeline-item\'>");
document.writeln("    <i class=\'layui-icon layui-timeline-axis\'>&#xe63f;</i>");
document.writeln("    <div class=\'layui-timeline-content layui-text\'>");
document.writeln("      <h3 class=\'layui-timeline-title\'>2005-09-01</h3>");
document.writeln("      <p>");
document.writeln("        武汉理工大学 211重点  全日制 正规院校");
document.writeln("        <br>计算机科学与技术");
document.writeln("        <br>本科");
document.writeln("        <br>学士");
document.writeln("        <br>CET4 520");
document.writeln("      </p>");
document.writeln("    </div>");
document.writeln("  </li>  ");
document.writeln("  <li class=\'layui-timeline-item\'>");
document.writeln("    <i class=\'layui-icon layui-timeline-axis\'>&#xe63f;</i>");
document.writeln("    <div class=\'layui-timeline-content layui-text\'>");
document.writeln("      <h3 class=\'layui-timeline-title\'>2002-09-01</h3>");
document.writeln("      <p>");
document.writeln("        湖北省嘉鱼县第一高级中学");
document.writeln("        <br>实验班 全日制 正规院校");
document.writeln("      </p>");
document.writeln("    </div>");
document.writeln("  </li>");
document.writeln("  <li class=\'layui-timeline-item\'>");
document.writeln("    <i class=\'layui-icon layui-timeline-axis\'>&#xe63f;</i>");
document.writeln("    <div class=\'layui-timeline-content layui-text\'>");
document.writeln("      <h3 class=\'layui-timeline-title\'>1999-09-01</h3>");
document.writeln("      <p>");
document.writeln("        湖北省嘉鱼县高铁镇八斗中学");
document.writeln("      </p>");
document.writeln("    </div>");
document.writeln("  </li>");
document.writeln("  <li class=\'layui-timeline-item\'>");
document.writeln("    <i class=\'layui-icon layui-timeline-axis\'>&#xe63f;</i>");
document.writeln("    <div class=\'layui-timeline-content layui-text\'>");
document.writeln("      <h3 class=\'layui-timeline-title\'>1993-09-01</h3>");
document.writeln("      <p>");
document.writeln("        湖北省赤壁市车埠镇熊家岭村小学");
document.writeln("      </p>");
document.writeln("    </div>");
document.writeln("  </li>");
document.writeln("  <li class=\'layui-timeline-item\'>");
document.writeln("    <i class=\'layui-icon layui-timeline-axis\'>&#xe63f;</i>");
document.writeln("    <div class=\'layui-timeline-content layui-text\'>");
document.writeln("      <h3 class=\'layui-timeline-title\'>1986-09-18</h3>");
document.writeln("      <p>");
document.writeln("        出生");
document.writeln("      </p>");
document.writeln("    </div>");
document.writeln("  </li>");
document.writeln("</ul>");
document.writeln("");
document.writeln("<div class=\'layui-row layui-col-space10\'>");
document.writeln("  <div class=\'layui-col-md4\'>");
document.writeln("    <button class=\'layui-btn layui-btn-fluid\'>共产党党员</button>");
document.writeln("  </div>");
document.writeln("  <div class=\'layui-col-md4\'>");
document.writeln("    <button class=\'layui-btn layui-btn-fluid layui-btn-warm\'>兼具金融科技经历</button>");
document.writeln("  </div>");
document.writeln("  <div class=\'layui-col-md4\'>");
document.writeln("  <button class=\'layui-btn layui-btn-fluid layui-btn-danger\'>乒乓球</button>");
document.writeln("  </div>");
document.writeln("  <div class=\'layui-col-md4\'>");
document.writeln("  <button class=\'layui-btn layui-btn-fluid layui-btn-warm\'>财报解读</button>");
document.writeln("  </div>");
document.writeln("  <div class=\'layui-col-md4\'>");
document.writeln("  <button class=\'layui-btn layui-btn-fluid layui-btn-normal\'>技术达人</button>");
document.writeln("  </div>");
document.writeln("  <div class=\'layui-col-md4\'>");
document.writeln("  <button class=\'layui-btn layui-btn-fluid layui-btn-normal\'>PYTHON</button>");
document.writeln("  </div>");
document.writeln("  <div class=\'layui-col-md4\'>");
document.writeln("  <button class=\'layui-btn layui-btn-fluid\'>ORACLE SQL</button>");
document.writeln("  </div>");
document.writeln("  <div class=\'layui-col-md4\'>");
document.writeln("  <button class=\'layui-btn layui-btn-fluid layui-btn-danger\'>JAVA</button>");
document.writeln("  </div>");
document.writeln("  <div class=\'layui-col-md4\'>");
document.writeln("    <button class=\'layui-btn layui-btn-fluid layui-btn-normal\'>信贷系统专家</button>");
document.writeln("  </div>");
document.writeln("</div>");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");